import type { PfTheme } from '../types'

export const THEME_FOCUS: PfTheme = {
  id: 'focus',
  name: 'Focus',
  description: 'High contrast. Near-zero motion. Calm by design.',
  version: '1.0',
  tokens: {
    '--pf-bg-base':             '#111110',
    '--pf-bg-surface':          '#1c1c1a',
    '--pf-bg-surface-alt':      '#262624',
    '--pf-bg-overlay':          'rgba(0,0,0,0.82)',
    '--pf-border':              '#2e2e2c',
    '--pf-border-strong':       '#44443f',
    '--pf-accent':              '#60a5fa',
    '--pf-accent-muted':        'rgba(96,165,250,0.12)',
    '--pf-accent-glow':         'rgba(96,165,250,0.15)',
    '--pf-positive':            '#4ade80',
    '--pf-warning':             '#fbbf24',
    '--pf-danger':              '#f87171',
    '--pf-positive-muted':      'rgba(74,222,128,0.1)',
    '--pf-warning-muted':       'rgba(251,191,36,0.1)',
    '--pf-danger-muted':        'rgba(248,113,113,0.1)',
    '--pf-text-primary':        '#fafaf9',
    '--pf-text-secondary':      '#a8a29e',
    '--pf-text-muted':          '#57534e',
    '--pf-font-ui':             "'Atkinson Hyperlegible', system-ui, sans-serif",
    '--pf-font-mono':           "'DM Mono', 'Courier New', monospace",
    '--pf-radius-sm':           '6px',
    '--pf-radius-md':           '10px',
    '--pf-radius-lg':           '16px',
    '--pf-heat-none':           '#1c1c1a',
    '--pf-heat-low':            '#14532d',
    '--pf-heat-mid':            '#fbbf24',
    '--pf-heat-high':           '#f87171',
    '--pf-duration-fast':       '150ms',
    '--pf-duration-normal':     '300ms',
    '--pf-duration-slow':       '600ms',
    '--pf-easing-default':      'linear',
    '--pf-easing-spring':       'linear',
    '--pf-easing-bounce':       'linear',
    '--pf-motion-intensity':    '0.05',
    '--pf-sidebar-width-full':  '252px',
    '--pf-sidebar-width-rail':  '68px',
    '--pf-icon-stroke':         '2',
    '--pf-icon-size-sm':        '18px',
    '--pf-icon-size-md':        '22px',
    '--pf-icon-size-lg':        '28px',
  },
}
