import type { PfTheme } from '../types'

export const THEME_LINEN: PfTheme = {
  id: 'linen',
  name: 'Linen',
  description: 'Warm cream light theme. Calm, tactile, paper-like.',
  version: '1.0',
  tokens: {
    '--pf-bg-base':             '#faf7f4',
    '--pf-bg-surface':          '#f5f0ea',
    '--pf-bg-surface-alt':      '#ede8e1',
    '--pf-bg-overlay':          'rgba(0,0,0,0.40)',
    '--pf-border':              '#ddd5c8',
    '--pf-border-strong':       '#c8bcaf',
    '--pf-accent':              '#92400e',
    '--pf-accent-muted':        'rgba(146,64,14,0.10)',
    '--pf-accent-glow':         'rgba(146,64,14,0.20)',
    '--pf-positive':            '#15803d',
    '--pf-warning':             '#b45309',
    '--pf-danger':              '#dc2626',
    '--pf-positive-muted':      'rgba(21,128,61,0.10)',
    '--pf-warning-muted':       'rgba(180,83,9,0.10)',
    '--pf-danger-muted':        'rgba(220,38,38,0.10)',
    '--pf-text-primary':        '#1c1410',
    '--pf-text-secondary':      '#6b5744',
    '--pf-text-muted':          '#a08878',
    '--pf-font-ui':             "'DM Sans', system-ui, sans-serif",
    '--pf-font-mono':           "'DM Mono', 'Courier New', monospace",
    '--pf-radius-sm':           '6px',
    '--pf-radius-md':           '10px',
    '--pf-radius-lg':           '16px',
    '--pf-heat-none':           '#ede8e1',
    '--pf-heat-low':            '#c8dfc0',
    '--pf-heat-mid':            '#d97706',
    '--pf-heat-high':           '#dc2626',
    '--pf-duration-fast':       '150ms',
    '--pf-duration-normal':     '300ms',
    '--pf-duration-slow':       '600ms',
    '--pf-easing-default':      'cubic-bezier(0.4, 0, 0.2, 1)',
    '--pf-easing-spring':       'cubic-bezier(0.34, 1.56, 0.64, 1)',
    '--pf-easing-bounce':       'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
    '--pf-motion-intensity':    '1',
    '--pf-sidebar-width-full':  '240px',
    '--pf-sidebar-width-rail':  '64px',
    '--pf-icon-stroke':         '2',
    '--pf-icon-size-sm':        '16px',
    '--pf-icon-size-md':        '20px',
    '--pf-icon-size-lg':        '24px',
  },
}
