import type { PfTheme } from '../types'

export const THEME_MIDNIGHT: PfTheme = {
  id: 'midnight',
  name: 'Midnight',
  description: 'Sleek dark dashboard. Elegant. Finance-grade.',
  version: '1.0',
  tokens: {
    '--pf-bg-base':             '#040810',
    '--pf-bg-surface':          '#070d1a',
    '--pf-bg-surface-alt':      '#0a1220',
    '--pf-bg-overlay':          'rgba(0,0,0,0.72)',
    '--pf-border':              '#1e293b',
    '--pf-border-strong':       '#334155',
    '--pf-accent':              '#14b8a6',
    '--pf-accent-muted':        'rgba(20,184,166,0.12)',
    '--pf-accent-glow':         'rgba(20,184,166,0.25)',
    '--pf-positive':            '#14b8a6',
    '--pf-warning':             '#f59e0b',
    '--pf-danger':              '#ef4444',
    '--pf-positive-muted':      'rgba(20,184,166,0.1)',
    '--pf-warning-muted':       'rgba(245,158,11,0.1)',
    '--pf-danger-muted':        'rgba(239,68,68,0.1)',
    '--pf-text-primary':        '#f1f5f9',
    '--pf-text-secondary':      '#94a3b8',
    '--pf-text-muted':          '#475569',
    '--pf-font-ui':             "'DM Sans', system-ui, sans-serif",
    '--pf-font-mono':           "'DM Mono', 'Courier New', monospace",
    '--pf-radius-sm':           '6px',
    '--pf-radius-md':           '10px',
    '--pf-radius-lg':           '16px',
    '--pf-heat-none':           '#0f172a',
    '--pf-heat-low':            '#134e4a',
    '--pf-heat-mid':            '#f59e0b',
    '--pf-heat-high':           '#ef4444',
    '--pf-duration-fast':       '150ms',
    '--pf-duration-normal':     '300ms',
    '--pf-duration-slow':       '600ms',
    '--pf-easing-default':      'cubic-bezier(0.4, 0, 0.2, 1)',
    '--pf-easing-spring':       'cubic-bezier(0.34, 1.56, 0.64, 1)',
    '--pf-easing-bounce':       'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
    '--pf-motion-intensity':    '1',
    '--pf-sidebar-width-full':  '240px',
    '--pf-sidebar-width-rail':  '64px',
    '--pf-icon-stroke':         '2',
    '--pf-icon-size-sm':        '16px',
    '--pf-icon-size-md':        '20px',
    '--pf-icon-size-lg':        '24px',
  },
}
