export const REQUIRED_TOKENS = [
  '--pf-bg-base',
  '--pf-accent',
  '--pf-text-primary',
  '--pf-border',
  '--pf-positive',
  '--pf-danger',
] as const

export const OPTIONAL_TOKENS = [
  '--pf-bg-surface',
  '--pf-bg-surface-alt',
  '--pf-bg-overlay',
  '--pf-border-strong',
  '--pf-accent-muted',
  '--pf-accent-glow',
  '--pf-warning',
  '--pf-positive-muted',
  '--pf-warning-muted',
  '--pf-danger-muted',
  '--pf-text-secondary',
  '--pf-text-muted',
  '--pf-font-ui',
  '--pf-font-mono',
  '--pf-radius-sm',
  '--pf-radius-md',
  '--pf-radius-lg',
  '--pf-heat-none',
  '--pf-heat-low',
  '--pf-heat-mid',
  '--pf-heat-high',
  '--pf-duration-fast',
  '--pf-duration-normal',
  '--pf-duration-slow',
  '--pf-easing-default',
  '--pf-easing-spring',
  '--pf-easing-bounce',
  '--pf-motion-intensity',
  '--pf-sidebar-width-full',
  '--pf-sidebar-width-rail',
  '--pf-icon-stroke',
  '--pf-icon-size-sm',
  '--pf-icon-size-md',
  '--pf-icon-size-lg',
] as const

export const ALL_TOKENS = [...REQUIRED_TOKENS, ...OPTIONAL_TOKENS] as const
